package corbaBanque;


/**
 * corbaBanque/IBanqueRemoteOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Banque.idl
 * Monday, November 10, 2025 10:48:36 AM WAT
 */

public interface IBanqueRemoteOperations
{

    // Créer un compte avec un paramètre "cpte" de type Compte en entrée
    void creerCompte (corbaBanque.Compte cpte);

    // Verser : deux paramètres en entrée "mt" de type float et "code" de type long
    void verser (float mt, int code);

    // Retirer : deux paramètres en entrée "mt" de type float et "code" de type long
    void retirer (float mt, int code);

    // Retourne un objet de type Compte sachant son code
    corbaBanque.Compte getCompte (int code);

    // Retourne un tableau de comptes
    corbaBanque.Compte[] getComptes ();

    // Conversion qui retourne un double possédé un paramètre "mt" de type float en entrée
    double conversion (float mt);
} // interface IBanqueRemoteOperations
