package corbaBanque;


/**
 * corbaBanque/IBanqueRemote.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Banque.idl
 * Monday, November 10, 2025 10:48:36 AM WAT
 */

public interface IBanqueRemote extends IBanqueRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface IBanqueRemote
